### ISSUE TITLE
[Question] Could you explain the normalization scheme you have used for PBRS and NYUV2 ? 

### ISSUE THREAD

**Issue by ghost** [MichaelRamamonjisoa/SharpNet#11]
In the dataset_manager.py file you normalize the depth map differently for the PBRS dataset and the NYU-V2 datasets. 

More precisely, in the PBRS dataset you divide the depth maps by 65535 whereas in the NYUV2 dataset you use 65.535.

Is there a specific reason behind these normalizations ? 

Thank you very much

**Comment by MichaelRamamonjisoa** [comment]
The idea was to have depth between 0 and 1 for both datasets. Since depth was saved in uint16 in PBRS, I simply divided by 65535 as you said. 
Then for NYUv2, ground truth data was in meters, while in PBRS it was in centimeters, which explains the factor 10 between the two datasets. Now that both data are expressed in the same units, fine tuning can go well.
Finally at test time, I re-multiply by the appropriate values to put the output values back to meters.

**Comment by ghost** [comment]
Thank you very much Michael !
