### ISSUE TITLE
Dear author, is it necessary to have a pretraining model of PBRS for training?

### ISSUE THREAD

**Issue by jialiang66** [MichaelRamamonjisoa/SharpNet#14]

**Comment by MichaelRamamonjisoa** [comment]
Hi, thank you for your interest. I don't think you absolutely need to pretrain on PBRS to train SharpNet.
However, if you want to use the geometry constraints between normals, depth, and contours, you will need to have ground truth data for those at the first training stage. 
I would advocate using synthetic data for the first training stage, since it will be much easier to impose geometrical constraints.

When finetuning on NYU, you don't need contours and normals ground truth.

**Comment by jialiang66** [comment]
However, this PBRS data set seems to be no longer available。 So I will not get your result if I directly use NYU data set for training？

**Comment by MichaelRamamonjisoa** [comment]
Indeed you won't get the same results. Sadly the research community has been strongly affected by the SUNCG problem, but in that specific case, I think using other realistic synthetic data could be sufficient to obtain comparable results.
