### ISSUE TITLE
Normal ground-truth for NYU dataset?

### ISSUE THREAD

**Issue by samaonline** [MichaelRamamonjisoa/SharpNet#16]
As shown in the following lines, the only available dataset, NYU, did not load normal (and boundary) GT? I also check and find normal loss (and geo loss) are 0. However, in Fig. 7, normal GTs are showed. Is there way to load normal GT from NYU dataset? Thanks!

https://github.com/MichaelRamamonjisoa/SharpNet/blob/master/utils.py#L141-L142

**Comment by MichaelRamamonjisoa** [comment]
Hi, 

Sorry for the delay. If you wish to train/test a network using ground truth normals, the two most popular ground truths are:
- Silberman's [here](https://cs.nyu.edu/~deigen/dnl/normals_gt.tgz)
- Ladicky's [here](https://www.inf.ethz.ch/personal/ladickyl/nyu_normals_gt.zip)

Also check out this work [MarrRevisited](https://github.com/aayushbansal/MarrRevisited) and this [repo](https://github.com/ankurhanda/sunrgbd-meta-data) (see compute.m) which provide matlab code to generate ground truth normals from Kinect data. 

You would then have to change the [NYUDataset](https://github.com/MichaelRamamonjisoa/SharpNet/blob/21156f7811650dfbc97962fb273c0ead9d14be29/dataset_manager.py#L177) class to enable reading normals (which are otherwise set to None).

Finally, the geo_loss should not be zero if you use the flags --depth --normal --boundary --consensus, as those are computed using predicted modalities (not ground truth).

The only thing you'll see changing by loading ground truth normal will the normals loss.
